make : Interpolation.h QB.cpp QC.cpp QD.cpp QE.cpp
	g++ -o B Interpolation.h QB.cpp
	./B
	g++ -o C Interpolation.h QC.cpp
	./C
	g++ -o D Interpolation.h QD.cpp
	./D
	g++ -o E Interpolation.h QE.cpp
	./E

