make : Header.h Q_B.cpp Q_C.cpp Q_D.cpp Q_E.cpp Q_F.cpp
	g++ -o B Header.h Q_B.cpp
	./B
	g++ -o C Header.h Q_C.cpp
	./C
	g++ -o D Header.h Q_D.cpp
	./D
	g++ -o E Header.h Q_E.cpp
	./E
	g++ -o F Header.h Q_F.cpp
	./F
